### ISSUE TITLE
Choose a cloud infrastructure

### ISSUE THREAD

**Issue by schafezp** [dituuj/TelegramTranslationApp#2]
This is a task to do a spike to determine what cloud hosting option we should chose.

Options:

1. Amazon web services
2. Google cloud platform
3. Azure
4. Digital ocean

Things to consider:

1. Pricing. We want to keep price down since this is a pet project. 
2. Language translation api: we need an api that supports Cantonese and ideally has a high limit on the free tier. 
3. Familiarity vs exploration: we could either pick a cloud platform we’re familiar with vs learn a new platform so we can experience learning new things.

**Comment by Panfilwk** [comment]
I have the most experience with AWS or DigitalOcean, but I'm down to do something exploratory into GCP or Azure though. DigitalOcean will probably be cheapest is my hunch, but AWS offers more flexibility if we want storage through s3 or something else alongside compute. Converting to something stateless and using AWS Lambda could also be cool

**Comment by Panfilwk** [comment]
Looks like we're bought into Azure, closing this...
